#################################################################################
# This file configures the CICS actions for the deployment
#################################################################################

db2_sys_def:
  package_maxrc: 4
  plan_maxrc: 4
  user: "{{ app_db2_user if app_db2_user is defined and app_db2_user else default_db2_user }}"
  package: "{{ app_db2_package if app_db2_package is defined and app_db2_package else default_db2_package }}"
  plan: "{{ app_db2_plan if app_db2_plan is defined and app_db2_plan else default_db2_plan }}"
  qualifier: "{{ app_db2_qualifier if app_db2_qualifier is defined and app_db2_qualifier else default_db2_qualifier }}"
  subsys: "{{ app_db2_subsys if app_db2_subsys is defined and app_db2_subsys else default_db2_subsys }}"
  package_jobcard: "{{default_pkg_jobcard}}"
  plan_jobcard: "{{default_plan_jobcard}}"
  package_action: "{{default_db2_action}}"
  plan_action: "{{default_db2_action}}"
  sdsnload: "{{default_db2_sdsnload}}"
  plan_pklist: "*.CBSAPK.*"