apiVersion: deploy.ibm.com/v1
kind: DeploymentPlan
metadata:
  name: base
  description: base
  version: 20250625.111627.889
  annotations:
    creation_timestamp: 20250625.091631.584
    engine:
      version: 3.0.5
      build: manual
      date: Thu Apr 24 00:41:15 CEST 2025
    package:
      path: /u/dbehm/git/june-engagement-workspace/ts1_change_base_delete/base/main/dbbbuild_2025-06-25_11-14-53/logs/base-rel-1.0.0-2025-06-25_11-14-53_delete.tar
      sha256: 0794d1a63a4c2109a95779f995d251bcbea4de39cfadf807f08bdf3e22bac4fb
activities:
- name: CONFIG
  description: |-
    Load the generic Wazi Deploy Configuration variables
    Specific for the Python implementation
  properties: []
  actions:
  - name: READ CONFIGURATION
    properties: []
    steps:
    - name: INCLUDE APPLICATION VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_application_vars
      artifacts: []
      types: []
      short_name: INCLUDE_APP_VARS
    - name: INCLUDE MIDDLEWARE VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_middleware_vars
      artifacts: []
      types: []
      short_name: INCLUDE_MIDDLEWARE_VARS
    - name: INCLUDE COMMON VARIABLES
      properties:
      - key: template
        value: include_vars
      - key: var_include_vars
        value: include_common_vars
      artifacts: []
      types: []
      short_name: INCLUDE_COMMON_VARS
    types: []
    short_name: CONFIG
  types: []
- name: PACKAGE
  description: |-
    This activity expands the package into the working directory
  properties: []
  actions:
  - name: PACKAGE
    properties: []
    steps:
    - name: PACKAGE
      properties: []
      artifacts: []
      types: []
    types: []
  types: []
  tags:
  - package
- name: DELETE_MODULES
  description: |-
    This activity is dedicated to the deletion of the artifacts from the PDS(E)s
  properties: []
  actions:
  - name: DELETE
    description: |-
      This action is applicable when the artifacts are deleted
    properties: []
    steps:
    - name: MEMBER_ARCHIVE
      description: |-
        This step backs up already installed artifacts into the backup PDS
      properties: []
      artifacts:
      - name: BAB1
        properties:
        - key: path
          value: bin/jcl/BAB1.JCL
        - key: githash
          value: 2e1b563d896167219c4527450ec57c9c6b71a934
        - key: giturl
          value: https://github.com/dennis-behm/base.git
        - key: wd_manifest_index
          value: 0
        - key: type
          value: JCL
        hash: 2e1b563d896167219c4527450ec57c9c6b71a934
      types: []
    - name: MEMBER_DELETE
      description: |-
        This step deletes the artifacts
      properties: []
      artifacts:
      - name: BAB1
        properties:
        - key: path
          value: bin/jcl/BAB1.JCL
        - key: githash
          value: 2e1b563d896167219c4527450ec57c9c6b71a934
        - key: giturl
          value: https://github.com/dennis-behm/base.git
        - key: wd_manifest_index
          value: 0
        - key: type
          value: JCL
        hash: 2e1b563d896167219c4527450ec57c9c6b71a934
      types: []
    types: []
  is_artifact: true
  types:
  - name: DBRM
  - name: LOAD
  - name: CICSLOAD
  - name: MAPLOAD
  - name: JCL
manifests:
- name: base
  description: base
  version: 20250625.111627.889
  annotations:
    creationTimestamp: 20250625.111627.889
    scmInfo:
      type: git
      uri: https://github.com/dennis-behm/base.git
      branch: main
      shortCommit: 2e1b563d896167219c4527450ec57c9c6b71a934
deployment_methods:
- apiVersion: deploy.ibm.com/v1
  kind: DeploymentMethod
  metadata:
    name: CICS
    description: |-
      This deployment method can be use for the deployment of an CICS application.
    version: 1.0.0
    annotations:
      deployVersion: 1.0.0
